### ISSUE TITLE
Errors in src-gen when there is upper case in the syntax epackage name

### ISSUE THREAD

**Issue by ebousse** [diverse-project/melange#52]
Hello :)

There are compilation errors in the generated code (src-gen) when the syntax EPackage name has some upper case letters in it.

To reproduce:
- Create an EMF project with an ecore model whose package name is "PackageThatRocks"
- Create an xDSML project with a Melange model referencing the ecore as syntax
- Right click, "Generate all"

And there are many compilation errors in the generated "src-gen".

From what I can try to guess: some generator code of Melange uses toLowerCase when writing a package name in a Java file, even though the real package name might have upper case in it

**Comment by ebousse** [comment]
Oh, and I was using Melange 0.1.0.201602 from a recent GEMOC Studio.

**Comment by tdegueul** [comment]
Hey, thanks for the report!

Indeed, we erroneously put every package name in lower case in the generated code. Who's putting uppercase in a Java package name anyway? Oh, EMF does... :)

Anyway, should be fixed in 64892fb. Pro tip: if you plan to use multiple root packages or subpackages, you are in trouble. But we may work on it if needed.

Cheers

**Comment by ebousse** [comment]
> Anyway, should be fixed in 64892fb. Pro tip: if you plan to use multiple root packages or subpackages, you are in trouble. But we may work on it if needed.

I'll keep that in mind, thanks!
